export const GET_ARTISTS_SUCCESS = 'GET_ARTISTS_SUCCESS';
export const GET_ARTISTS_ERROR = 'GET_ARTISTS_ERROR';
export const POST_NEW_ARTISTS_SUCCESS = 'POST_NEW_ARTISTS_SUCCESS';
export const POST_NEW_ARTISTS_ERROR = 'POST_NEW_ARTIST_ERROR';
export const PUBLISH_ARTIST_SUCCESS = 'PUBLISH_ARTIST_SUCCESS';
export const PUBLISH_ARTIST_ERROR = 'PUBLISH_ARTIST_ERROR';
export const DELETE_ARTIST_SUCCESS = 'DELETE_ARTIST_SUCCESS';
export const DELETE_ARTIST_ERROR = 'DELETE_ARTIST_ERROR';

export const GET_ALBUMS_SUCCESS = 'GET_ALBUMS_SUCCESS';
export const GET_ALBUMS_ERROR = 'GET_ALBUMS_ERROR';
export const POST_ALBUMS_SUCCESS = 'POST_ALBUMS_SUCCESS';
export const POST_ALBUMS_ERROR = 'POST_ALBUMS_ERROR';
export const PUBLISH_ALBUM_SUCCESS = 'PUBLISH_ALBUM_SUCCESS';
export const PUBLISH_ALBUM_ERROR = 'PUBLISH_ALBUM_ERROR';
export const DELETE_ALBUM_SUCCESS = 'DELETE_ALBUM_SUCCESS';
export const DELETE_ALBUM_ERROR = 'DELETE_ALBUM_ERROR';

export const GET_TRACKS_SUCCESS = 'GET_TRACKS_SUCCESS';
export const GET_TRACKS_ERROR = 'GET_TRACKS_ERROR';
export const POST_NEW_TRACK_SUCCESS = 'POST_NEW_TRACK_SUCCESS';
export const POST_NEW_TRACK_ERROR = 'POST_NEW_TRACK_ERROR';
export const POST_TRACKS_SUCCESS = 'POST_TRACKS_SUCCESS';
export const POST_TRACKS_ERROR = 'POST_TRACKS_ERROR';
export const PUBLISH_TRACK_SUCCESS = 'PUBLISH_TRACK_SUCCESS';
export const PUBLISH_TRACK_ERROR = 'PUBLISH_TRACK_ERROR';
export const DELETE_TRACK_SUCCESS = 'DELETE_TRACK_SUCCESS';
export const DELETE_TRACK_ERROR = 'DELETE_TRACK_ERROR';


export const GET_TRACKSHISTORY_SUCCESS = 'GET_TRACKHISTORY_SUCCESS';
export const GET_TRACKHISTORY_ERROR = 'GET_TRACKHISTORY_ERROR';

export const REGISTER_USER_SUCCESS = 'REGISTER_USER_SUCCESS';
export const REGISTER_USER_ERROR = 'REGISTER_USER_ERROR';

export const LOGIN_USER_SUCCESS = 'LOGIN_USER_SUCCESS';
export const LOGIN_USER_ERROR = 'LOGIN_USER_ERROR';

export const LOGOUT_USER = 'LOGOUT_USER';