export const GET_ARTISTS_SUCCESS = 'GET_ARTISTS_SUCCESS';
export const GET_ARTISTS_ERROR = 'GET_ARTISTS_ERROR';

export const GET_ALBUMS_SUCCESS = 'GET_ALBUMS_SUCCESS';
export const GET_ALBUMS_ERROR = 'GET_ALBUMS_ERROR';

export const GET_TRACKS_SUCCESS = 'GET_TRACKS_SUCCESS';
export const GET_TRACKS_ERROR = 'GET_TRACKS_ERROR';
export const POST_TRACKS_SUCCESS = 'POST_TRACKS_SUCCESS';
export const POST_TRACKS_ERROR = 'POST_TRACKS_ERROR';
export const GET_TRACKSHISTORY_SUCCESS = 'GET_TRACKHISTORY_SUCCESS';
export const GET_TRACKHISTORY_ERROR = 'GET_TRACKHISTORY_ERROR';

export const REGISTER_USER_SUCCESS = 'REGISTER_USER_SUCCESS';
export const REGISTER_USER_ERROR = 'REGISTER_USER_ERROR';

export const LOGIN_USER_SUCCESS = 'LOGIN_USER_SUCCESS';
export const LOGIN_USER_ERROR = 'LOGIN_USER_ERROR';